palavras_com_dicas  = [ {"palavra": "amor", "dica": "Sentimento forte de afeto."},
    {"palavra": "felicidade", "dica": "Estado de contentamento."},
    {"palavra": "universo", "dica": "Tudo o que existe ao nosso redor."},
    {"palavra": "coração", "dica": "Órgão vital do corpo humano."},
    {"palavra": "alegria", "dica": "Sentimento de prazer e contentamento."},
    {"palavra": "escola", "dica": "Lugar onde se aprende."},
    {"palavra": "biblioteca", "dica": "Local que reúne livros."},
    {"palavra": "computador", "dica": "Máquina usada para processar informações."},
    {"palavra": "tristeza", "dica": "Sentimento de dor emocional."},
    {"palavra": "obsoleto", "dica": "Algo que está fora de uso ou antiquado."},
    {"palavra": "taciturno", "dica": "Pessoa que fala pouco ou é reservada."},
    {"palavra": "habitual", "dica": "Algo que acontece com frequência."},
    {"palavra": "rotineiro", "dica": "Relacionado a rotina, algo repetitivo."},
    {"palavra": "carro", "dica": "Veículo motorizado usado para transporte."},
    {"palavra": "cristalino", "dica": "Algo que é claro e transparente."},
    {"palavra": "rapadura", "dica": "Doce tradicional feito de cana-de-açúcar."},
    {"palavra": "ordem", "dica": "Estado de organização."},
    {"palavra": "sol", "dica": "Estrela que ilumina e aquece a Terra."},
    {"palavra": "lua", "dica": "Satélite natural da Terra."},
    {"palavra": "estrela", "dica": "Corpo celeste que brilha no céu."},
    {"palavra": "amoroso", "dica": "Pessoa que demonstra carinho e afeto."},
    {"palavra": "desafio", "dica": "Situação que exige esforço e habilidade."},
    {"palavra": "inovação", "dica": "Ato de criar algo novo ou diferente."},
    {"palavra": "esperança", "dica": "Sentimento de confiança no futuro."},
    {"palavra": "amizade", "dica": "Relação de afeto e confiança entre pessoas."},
    {"palavra": "solidão", "dica": "Estado de estar sem companhia."},
    {"palavra": "música", "dica": "Arte de combinar sons de forma agradável."},
    {"palavra": "cultura", "dica": "Conjunto de costumes, crenças e práticas de um grupo."},
    {"palavra": "paz", "dica": "Estado de tranquilidade e harmonia."},
    {"palavra": "guerra", "dica": "Conflito armado entre países ou grupos."},
    {"palavra": "livro", "dica": "Conjunto de folhas encadernadas com texto ou ilustração."},
    {"palavra": "violência", "dica": "Ato de usar força física para causar dano."},
    {"palavra": "ambiente", "dica": "Espaço ou meio ao redor de algo ou alguém."},
    {"palavra": "inteligente", "dica": "Pessoa que demonstra grande capacidade cognitiva."},
    {"palavra": "genial", "dica": "Pessoa ou ideia extremamente criativa e inovadora."},
    {"palavra": "sabor", "dica": "Sensação que percebemos ao provar alimentos."},
    {"palavra": "aroma", "dica": "Cheiro agradável que vem de uma substância."},
    {"palavra": "sabedoria", "dica": "Conhecimento profundo adquirido com o tempo."},
    {"palavra": "mistério", "dica": "Algo que não pode ser facilmente explicado."},
    {"palavra": "escuridão", "dica": "Falta de luz, ambiente sombrio."},
    {"palavra": "luz", "dica": "Radiação visível que ilumina o ambiente."},
    {"palavra": "floresta", "dica": "Grande área coberta por árvores e vegetação."},
    {"palavra": "oceano", "dica": "Grande corpo de água salgada que cobre a maior parte da Terra."},
    {"palavra": "rio", "dica": "Corrente de água que flui em direção ao mar."},
    {"palavra": "montanha", "dica": "Elevação natural da superfície terrestre."},
    {"palavra": "vulcão", "dica": "Montanha que libera lava e gases do interior da Terra."},
    {"palavra": "deserto", "dica": "Região árida, com pouca ou nenhuma vegetação."},
    {"palavra": "chuva", "dica": "Precipitação de gotas de água da atmosfera."},
    {"palavra": "neve", "dica": "Precipitação de cristais de gelo."},
    {"palavra": "vento", "dica": "Movimento do ar na atmosfera."},
    {"palavra": "mar", "dica": "Grande extensão de água salgada."},
    {"palavra": "praia", "dica": "Área de areia à beira-mar."},
    {"palavra": "campo", "dica": "Área de terra usada para cultivo ou pastagem."},
    {"palavra": "cidade", "dica": "Área urbana com grande concentração de pessoas e edifícios."},
    {"palavra": "bairro", "dica": "Divisão de uma cidade ou município."},
    {"palavra": "museu", "dica": "Instituição que conserva e exibe coleções históricas ou artísticas."},
    {"palavra": "teatro", "dica": "Espaço para apresentações dramáticas e artísticas."},
    {"palavra": "cinema", "dica": "Espaço onde filmes são exibidos ao público."},
    {"palavra": "dança", "dica": "Expressão artística através de movimentos corporais."},
    {"palavra": "arte", "dica": "Atividade humana de criar obras que exprimem ideias ou emoções."},
    {"palavra": "tecnologia", "dica": "Aplicação de conhecimentos para criar ferramentas e dispositivos."},
    {"palavra": "inovador", "dica": "Pessoa que introduz novas ideias ou métodos."},
    {"palavra": "acidente", "dica": "Evento inesperado que causa danos."},
    {"palavra": "conhecimento", "dica": "Informação adquirida por meio do aprendizado."},
    {"palavra": "ciência", "dica": "Conhecimento sistemático adquirido por observação e experimentação."},
    {"palavra": "professor", "dica": "Pessoa que ensina, transmite conhecimentos."},
    {"palavra": "estudo", "dica": "Ato de aprender e se aprofundar em determinado tema."},
    {"palavra": "esforço", "dica": "Emprego de energia para alcançar um objetivo."},
    {"palavra": "trabalho", "dica": "Atividade que visa a produção de algo ou a obtenção de lucro."},
    {"palavra": "carreira", "dica": "Trajetória profissional ou ocupacional ao longo da vida."},
    {"palavra": "emprego", "dica": "Posição ou função no mercado de trabalho."},
    {"palavra": "empresa", "dica": "Organização que visa lucro através de produtos ou serviços."},
    {"palavra": "capital", "dica": "Recursos financeiros ou bens utilizados para investimento."},
    {"palavra": "mercado", "dica": "Espaço onde ocorre a troca de bens e serviços."},
    {"palavra": "economia", "dica": "Ciência que estuda a produção, distribuição e consumo de bens."},
    {"palavra": "finanças", "dica": "Gestão de recursos monetários e investimentos."},
    {"palavra": "investimento", "dica": "Ação de aplicar recursos visando a obtenção de lucro."},
    {"palavra": "indústria", "dica": "Setor econômico que transforma matérias-primas em produtos."},
    {"palavra": "teoria", "dica": "Conjunto de ideias que explicam fenômenos observados."},
    {"palavra": "prática", "dica": "Aplicação de conhecimentos teóricos na realidade."},
    {"palavra": "experiência", "dica": "Conhecimento adquirido por vivência ou prática."},
    {"palavra": "habilidade", "dica": "Capacidade de realizar uma tarefa com destreza."},
    {"palavra": "intuição", "dica": "Capacidade de entender algo sem raciocínio lógico."},
    {"palavra": "criatividade", "dica": "Capacidade de criar ou inventar coisas novas."},
    {"palavra": "imaginação", "dica": "Faculdade de criar imagens ou ideias na mente."},
    {"palavra": "inspiração", "dica": "Estímulo criativo ou motivacional para realizar algo."},
    {"palavra": "artefato", "dica": "Objeto criado por mãos humanas, especialmente com finalidade prática."},
    {"palavra": "invenção", "dica": "Criação de algo novo que não existia antes."},
    {"palavra": "design", "dica": "Processo de planejar e criar produtos ou serviços com estética e funcionalidade."},
    {"palavra": "moda", "dica": "Estilo ou tendência popular em roupas e acessórios."},
    {"palavra": "beleza", "dica": "Qualidade que agrada aos sentidos, especialmente à visão."},
    {"palavra": "estilo", "dica": "Forma particular de expressão, comportamento ou aparência."},
    {"palavra": "luxo", "dica": "Condição de riqueza e abundância, geralmente associada ao consumo excessivo."},
    {"palavra": "elegância", "dica": "Qualidade de ser refinado e bem-apessoado."},
    {"palavra": "comodidade", "dica": "Qualidade de ser confortável e fácil de usar."},
    {"palavra": "conforto", "dica": "Sensação de bem-estar físico e psicológico."},
    {"palavra": "saúde", "dica": "Estado de completo bem-estar físico, mental e social."},
    {"palavra": "doença", "dica": "Alteração do estado normal de saúde."},
    {"palavra": "tratamento", "dica": "Conjunto de ações para curar ou aliviar uma doença."},
    {"palavra": "medicina", "dica": "Ciência que estuda as doenças e suas formas de tratamento."},
    {"palavra": "vacina", "dica": "Substância utilizada para prevenir doenças."},
    {"palavra": "cura", "dica": "Restabelecimento da saúde após uma doença."},
    {"palavra": "prevenção", "dica": "Ato de evitar que algo negativo aconteça."},
    {"palavra": "atividade física", "dica": "Qualquer movimento corporal que exija gasto de energia."},
    {"palavra": "esporte", "dica": "Atividade física praticada com fins recreativos ou competitivos."},
    {"palavra": "alimento", "dica": "Substância consumida para fornecer nutrientes ao corpo."},
    {"palavra": "nutrição", "dica": "Processo de ingestão e utilização de alimentos pelo organismo."},
    {"palavra": "dieta", "dica": "Conjunto de alimentos consumidos regularmente."},
    {"palavra": "caloria", "dica": "Unidade de medida de energia presente nos alimentos."},
    {"palavra": "hidratação", "dica": "Ato de fornecer líquidos ao corpo."},
    {"palavra": "descanso", "dica": "Período de repouso para recuperação de forças."},
    {"palavra": "sono", "dica": "Estado natural de descanso e recuperação do corpo e mente."},
    {"palavra": "relaxamento", "dica": "Estado de tranquilidade e redução do estresse."},
    {"palavra": "meditação", "dica": "Prática de foco mental para alcançar a calma e clareza."},
    {"palavra": "yoga", "dica": "Prática física e mental que visa o equilíbrio e bem-estar."},
    {"palavra": "respiração", "dica": "Ato de inspirar e expirar ar dos pulmões."},
    {"palavra": "mentalidade", "dica": "Forma de pensar ou atitude em relação à vida."},
    {"palavra": "autoestima", "dica": "Avaliação positiva ou negativa que alguém faz de si mesmo."},
    {"palavra": "autoconfiança", "dica": "Confiança nas próprias habilidades e qualidades."},
    {"palavra": "felicidade", "dica": "Estado de prazer e satisfação plena."},
    {"palavra": "coragem", "dica": "Capacidade de enfrentar situações difíceis sem medo."},
    {"palavra": "sabão", "dica": "Produto usado para limpeza."},
    {"palavra": "pessoa", "dica": "Indivíduo humano."},
    {"palavra": "piano", "dica": "Instrumento musical de teclas brancas e pretas."},
    {"palavra": "jogo", "dica": "Atividade recreativa com regras."},
    {"palavra": "natureza", "dica": "Tudo o que é criado sem intervenção humana."},
    {"palavra": "ar", "dica": "Mistura de gases que compõem a atmosfera."},
    {"palavra": "rio", "dica": "Curso de água que flui por terra."},
    {"palavra": "futuro", "dica": "Período que ainda está por vir."},
    {"palavra": "presente", "dica": "Momento atual."},
    {"palavra": "passado", "dica": "Período de tempo anterior ao presente."},
    {"palavra": "jardim", "dica": "Espaço destinado ao cultivo de plantas."},
    {"palavra": "criança", "dica": "Pessoa jovem, em fase de desenvolvimento."},
    {"palavra": "adulto", "dica": "Pessoa que atingiu a maturidade."},
    {"palavra": "livraria", "dica": "Estabelecimento que vende livros."},
    {"palavra": "mercado", "dica": "Local para compra e venda de produtos."},
    {"palavra": "praia", "dica": "Área de areia ao lado do mar."},
    {"palavra": "floresta", "dica": "Grande área coberta por árvores."},
    {"palavra": "ilha", "dica": "Porção de terra cercada de água."},
    {"palavra": "escada", "dica": "Estrutura usada para subir ou descer."},
    {"palavra": "janela", "dica": "Abertura em uma parede, geralmente com vidro."},
    {"palavra": "porta", "dica": "Estrutura que permite a passagem entre ambientes."},
    {"palavra": "roupa", "dica": "Vestimenta usada no corpo."},
    {"palavra": "calçado", "dica": "Peça de vestuário para os pés."},
    {"palavra": "cabelo", "dica": "Filamentos que crescem na cabeça humana."},
    {"palavra": "mão", "dica": "Parte do corpo usada para pegar objetos."},
    {"palavra": "pé", "dica": "Parte do corpo usada para caminhar."},
    {"palavra": "olho", "dica": "Órgão responsável pela visão."},
    {"palavra": "boca", "dica": "Abertura do rosto usada para comer e falar."},
    {"palavra": "ouvido", "dica": "Órgão responsável pela audição."},
    {"palavra": "nariz", "dica": "Órgão responsável pelo olfato."},
    {"palavra": "flor", "dica": "Estrutura reprodutiva das plantas."},
    {"palavra": "fruta", "dica": "Alimento proveniente de plantas, geralmente doce."},
    {"palavra": "vegetal", "dica": "Planta que pode ser consumida como alimento."},
    {"palavra": "animal", "dica": "Ser vivo que se alimenta e se move."},
    {"palavra": "inseto", "dica": "Pequeno animal com exoesqueleto e antenas."},
    {"palavra": "morcego", "dica": "Mamífero voador que se alimenta de insetos ou frutas."},
    {"palavra": "gato", "dica": "Animal doméstico, mamífero felino."},
    {"palavra": "cachorro", "dica": "Animal doméstico, mamífero canino."},
    {"palavra": "pássaro", "dica": "Animal que tem asas e pode voar."},
    {"palavra": "peixe", "dica": "Animal aquático com brânquias."},
    {"palavra": "cavalo", "dica": "Animal de grande porte usado para montar."},
    {"palavra": "vaca", "dica": "Animal doméstico, geralmente usado para produzir leite."},
    {"palavra": "ovelha", "dica": "Animal domesticado, conhecido pela lã."},
    {"palavra": "galinha", "dica": "Ave domesticada, que produz ovos."},
    {"palavra": "carne", "dica": "Parte comestível do corpo de animais."},
    {"palavra": "leite", "dica": "Líquido produzido por mamíferos para alimentar seus filhotes."},
    {"palavra": "queijo", "dica": "Produto alimentício feito a partir do leite."},
    {"palavra": "ovo", "dica": "Produto reprodutivo de aves, comum na alimentação."},
    {"palavra": "pão", "dica": "Alimento básico feito de farinha, água e fermento."},
    {"palavra": "arroz", "dica": "Grão consumido como alimento principal em muitas culturas."},
    {"palavra": "feijão", "dica": "Grão rico em proteínas, comum em diversas dietas."},
    {"palavra": "batata", "dica": "Raiz comestível e rica em carboidratos."},
    {"palavra": "frango", "dica": "Ave doméstica criada para consumo de carne."},
    {"palavra": "carneiro", "dica": "Macho da ovelha, criado por sua carne e lã."},
    {"palavra": "bife", "dica": "Fatias de carne geralmente de boi."},
    {"palavra": "salada", "dica": "Comida fria composta principalmente por folhas e legumes."},
    {"palavra": "sopa", "dica": "Prato líquido geralmente feito com legumes ou carnes."},
    {"palavra": "lanche", "dica": "Refeição rápida, geralmente entre as principais refeições."},
    {"palavra": "almoço", "dica": "Refeição principal consumida no meio do dia."},
    {"palavra": "jantar", "dica": "Refeição consumida à noite."},
    {"palavra": "refeição", "dica": "Qualquer momento de consumo de alimentos."},
    {"palavra": "café", "dica": "Bebida feita a partir de grãos torrados e moídos."},
    {"palavra": "chá", "dica": "Bebida feita a partir de folhas ou flores de plantas."},
    {"palavra": "água", "dica": "Líquido essencial para a vida humana e animal."},
    {"palavra": "suco", "dica": "Bebida extraída de frutas ou vegetais."},
    {"palavra": "refrigerante", "dica": "Bebida gaseificada, geralmente doce."},
    {"palavra": "energia", "dica": "Capacidade de realizar trabalho ou causar mudanças."},
    {"palavra": "fogo", "dica": "Combustão que gera calor e luz."},
    {"palavra": "gelo", "dica": "Água congelada."},
    {"palavra": "brisa", "dica": "Vento suave e refrescante."},
    {"palavra": "tempestade", "dica": "Condição climática com ventos fortes e chuva intensa."},
    {"palavra": "neblina", "dica": "Nebulosa que reduz a visibilidade."},
    {"palavra": "tornado", "dica": "Vento forte e em espiral que causa destruição."},
    {"palavra": "furacão", "dica": "Tempestade tropical com ventos extremamente fortes."},
    {"palavra": "tsunami", "dica": "Ondas gigantes causadas por terremotos no fundo do mar."},
    {"palavra": "terremoto", "dica": "Movimento súbito da crosta terrestre."},
    {"palavra": "erupção", "dica": "Expulsão de lava e gases por um vulcão."},
    {"palavra": "avalanche", "dica": "Deslizamento de neve ou rochas em áreas montanhosas."},
    {"palavra": "sol", "dica": "Estrela que fornece luz e calor para a Terra."},
    {"palavra": "lua", "dica": "Satélite natural da Terra."},
    {"palavra": "estrela", "dica": "Corpo celeste visível no céu à noite."},
    {"palavra": "planeta", "dica": "Corpo celeste que orbita uma estrela."},
    {"palavra": "galáxia", "dica": "Conjunto de estrelas, planetas e outros corpos celestes."},
    {"palavra": "astronomia", "dica": "Ciência que estuda os corpos celestes."},
    {"palavra": "física", "dica": "Ciência que estuda as leis da natureza."},
    {"palavra": "química", "dica": "Ciência que estuda as substâncias e suas transformações."},
    {"palavra": "biologia", "dica": "Ciência que estuda os seres vivos."},
    {"palavra": "matemática", "dica": "Ciência dos números e das formas."},
    {"palavra": "história", "dica": "Estudo dos acontecimentos passados."},
    {"palavra": "geografia", "dica": "Estudo da Terra e seus fenômenos."},
    {"palavra": "literatura", "dica": "Conjunto de obras escritas que expressam ideias e sentimentos."},
    {"palavra": "biologia", "dica": "Ciência que estuda os seres vivos."},
    {"palavra": "matemática", "dica": "Ciência dos números e das formas."},
    {"palavra": "história", "dica": "Estudo dos acontecimentos passados."},
    {"palavra": "geografia", "dica": "Estudo da Terra e seus fenômenos."},
    {"palavra": "literatura", "dica": "Conjunto de obras escritas que expressam ideias e sentimentos."},
    {"palavra": "filosofia", "dica": "Estudo dos problemas fundamentais sobre a existência e o conhecimento."},
    {"palavra": "sociedade", "dica": "Conjunto de pessoas que compartilham cultura e território."},
    {"palavra": "governo", "dica": "Autoridade responsável por administrar um país ou território."},
    {"palavra": "democracia", "dica": "Sistema de governo em que o povo participa das decisões."},
    {"palavra": "justiça", "dica": "Princípio que busca a equidade e os direitos."},
    {"palavra": "direito", "dica": "Conjunto de normas que regulam a convivência em sociedade."},
    {"palavra": "liberdade", "dica": "Direito de agir de acordo com a própria vontade."},
    {"palavra": "igualdade", "dica": "Princípio de tratamento sem discriminação."},
]
